name: zidship
services:
  # PostgreSQL with pgvector extension
  db:
    image: postgres:14
    container_name: zidship_db
    environment:
      POSTGRES_USER: zidship_user
      POSTGRES_PASSWORD: zidship_pass
      POSTGRES_DB: zidship_db
    ports:
      - '5432:5432'
    volumes:
      - zidship_volume:/var/lib/postgresql/data

volumes:
  zidship_volume:
